name: Automated Build, Tests and Linting

on:
  push:
  pull_request:
    branches:
      - master
jobs:
  lint-build-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Linting
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test

      - name: Code Coverage
        uses: codecov/codecov-action@v1
